services:
  - type: web
    name: library-management-backend
    env: docker
    buildCommand: docker build -t library-backend .
    startCommand: ./main
    envVars:
      - key: PORT
        value: 8080
      - key: GIN_MODE
        value: release
